-- Censuren i grind A och vägpunktsgrinden (kort #252 förslag 1, DECISIONS #352) — bara antal, ingen felkvot.
-- För varje kall målhalvtimme (yta <= 5 °C, #75 och radvakten) i 60 dygn: hur många av målets fem närmaste stationer inom 50 km
-- har en arkivrad i samma halvtimme? En granne som saknas i en kall halvtimme är varm och torr eller nere — arkivet kan inte skilja
-- dem (den levande ingesten sparar bara yta <= 5 eller nederbörd), så andelen är ett TAK för censuren. Grannvalet är grindarnas
-- (fem närmaste inom 50 km), ordnat på plan KNN över stationernas läge i weather_latest — ungefär, inte exakt, grindens urval.
-- Karantänen och den långsamma vakten är inte med (1–3 stationer per dygn). Grannens rad slås upp i primärnyckeln
-- (station_id, sample_time); första versionen grupperade hela arkivet och föll på tidsgränsen. Körs med dbknapp: en sats per rad.
WITH gr AS (SELECT a.station_id AS s, b.station_id AS n FROM weather_latest a CROSS JOIN LATERAL (SELECT b.station_id FROM weather_latest b WHERE b.station_id <> a.station_id AND b.geom IS NOT NULL AND ST_DWithin(a.geom::geography, b.geom::geography, 50000) ORDER BY a.geom <-> b.geom LIMIT 5) b WHERE a.geom IS NOT NULL), mal AS (SELECT station_id, floor(extract(epoch FROM sample_time) / 1800)::bigint AS b, max(surface_temp_c) AS yta FROM weather_observations WHERE sample_time > now() - interval '60 days' AND surface_temp_c <= 5 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12 AND (air_temp_c < 10 OR air_temp_c - surface_temp_c < 8) GROUP BY 1, 2), par AS (SELECT m.station_id, m.b, m.yta, EXISTS (SELECT 1 FROM weather_observations x WHERE x.station_id = g.n AND x.sample_time >= to_timestamp(m.b * 1800) AND x.sample_time < to_timestamp((m.b + 1) * 1800) AND x.surface_temp_c IS NOT NULL AND x.air_temp_c IS NOT NULL AND x.surface_temp_c >= x.air_temp_c - 12) AS med FROM mal m JOIN gr g ON g.s = m.station_id) SELECT 'kalla (yta <= 5)' AS urval, count(DISTINCT (station_id, b)) AS malhalvtimmar, count(*) AS grannplatser, count(*) FILTER (WHERE med) AS med_rad, count(*) FILTER (WHERE NOT med) AS saknas, round(100.0 * count(*) FILTER (WHERE NOT med) / nullif(count(*), 0), 1) AS andel_saknas_pct FROM par UNION ALL SELECT 'frysnära (yta <= 1)', count(DISTINCT (station_id, b)), count(*), count(*) FILTER (WHERE med), count(*) FILTER (WHERE NOT med), round(100.0 * count(*) FILTER (WHERE NOT med) / nullif(count(*), 0), 1) FROM par WHERE yta <= 1
WITH gr AS (SELECT a.station_id AS s, b.station_id AS n FROM weather_latest a CROSS JOIN LATERAL (SELECT b.station_id FROM weather_latest b WHERE b.station_id <> a.station_id AND b.geom IS NOT NULL AND ST_DWithin(a.geom::geography, b.geom::geography, 50000) ORDER BY a.geom <-> b.geom LIMIT 5) b WHERE a.geom IS NOT NULL), mal AS (SELECT station_id, floor(extract(epoch FROM sample_time) / 1800)::bigint AS b FROM weather_observations WHERE sample_time > now() - interval '60 days' AND surface_temp_c <= 5 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12 AND (air_temp_c < 10 OR air_temp_c - surface_temp_c < 8) GROUP BY 1, 2), per AS (SELECT m.station_id, m.b, count(g.n) AS grannar, count(*) FILTER (WHERE EXISTS (SELECT 1 FROM weather_observations x WHERE x.station_id = g.n AND x.sample_time >= to_timestamp(m.b * 1800) AND x.sample_time < to_timestamp((m.b + 1) * 1800) AND x.surface_temp_c IS NOT NULL AND x.air_temp_c IS NOT NULL AND x.surface_temp_c >= x.air_temp_c - 12)) AS med FROM mal m LEFT JOIN gr g ON g.s = m.station_id GROUP BY 1, 2) SELECT grannar, med AS grannar_med_rad, count(*) AS malhalvtimmar FROM per GROUP BY 1, 2 ORDER BY 1, 2
SELECT count(DISTINCT (sample_time AT TIME ZONE 'UTC')::date) AS dygn_med_rader_60d FROM weather_observations WHERE sample_time > now() - 60 * interval '1 day'
SELECT least((SELECT min(dag) FROM arkiv_export), (SELECT min(sample_time) FROM weather_observations)::date)::text AS arkivets_borjan
