-- DJUR PÅ VÄGEN: TRAFIKVERKET MOT POLISEN (Bengts frågor 22/9: hur snabbt rapporterar Trafikverket, och vem är först när båda
-- rapporterar samma händelse?). Bara läsande. Bärare: sql/029_brott_index.sql (CREATE INDEX IF NOT EXISTS).
-- Källor: situation_archive (Trafikverket, ingest-live varje minut: first_seen högst en minut efter publicering) och polisen_events
-- (Polisens öppna API, bara typen "Trafikolycka, vilt", hämtas en gång i timmen: ingested_at kan ligga upp till en timme efter).
-- Polisens position är LÄNETS MITTPUNKT (DECISIONS #13), så ihopparningen är ungefärlig: samma vägnummer, Trafikverkets punkt inom
-- 150 km från polisens länspunkt, och starttiderna inom 3 h; närmast i tid vinner. Trafikverkets sida: djur på vägen ELLER en olycka
-- vars text nämner vilt eller ett djurslag. Vem som är först jämförs på källornas EGNA tider, inte på när vi hämtade dem.
-- Kör: varje sats på en rad i dbknapp (atgard migrera, fil sql/029_brott_index.sql, bevis = satserna).

SELECT 'trafikverket djur på vägen' AS kalla, count(*) AS handelser_14d, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM first_seen - start_time) / 60)::numeric, 1) AS median_min_start_till_oss, round(percentile_cont(0.9) WITHIN GROUP (ORDER BY extract(epoch FROM first_seen - start_time) / 60)::numeric, 1) AS p90_min, count(*) FILTER (WHERE first_seen - start_time <= interval '2 minutes') AS inom_2_min, count(*) FILTER (WHERE first_seen - start_time > interval '30 minutes') AS over_30_min, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM end_time - start_time) / 60)::numeric) AS median_giltig_min, count(*) FILTER (WHERE message ~* '(älg|rådjur|hjort|vildsvin|renar|ren |häst|nötkreatur|kor |får)') AS med_djurslag, count(*) FILTER (WHERE road_number IS NOT NULL) AS med_vagnummer FROM situation_archive WHERE message_type_value = 'AnimalPresenceObstruction' AND first_seen > now() - interval '14 days'

SELECT 'polisen trafikolycka vilt' AS kalla, count(*) AS handelser_14d, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM ingested_at - datetime) / 60)::numeric, 1) AS median_min_till_oss_timvis, round(percentile_cont(0.9) WITHIN GROUP (ORDER BY extract(epoch FROM ingested_at - datetime) / 60)::numeric, 1) AS p90_min, count(*) FILTER (WHERE road_number IS NOT NULL) AS med_vagnummer, count(*) FILTER (WHERE species IS NOT NULL) AS med_djurslag FROM polisen_events WHERE datetime > now() - interval '14 days'

WITH norm AS (SELECT 1), p AS (SELECT event_id, datetime, ingested_at, geom, replace(substring(upper(road_number) from 'E ?[0-9]+|[0-9]+'), ' ', '') AS vag FROM polisen_events WHERE datetime > now() - interval '14 days' AND road_number IS NOT NULL), t AS (SELECT deviation_id, message_type_value, start_time, first_seen, geom, replace(substring(upper(road_number) from 'E ?[0-9]+|[0-9]+'), ' ', '') AS vag FROM situation_archive WHERE first_seen > now() - interval '21 days' AND road_number IS NOT NULL AND geom IS NOT NULL AND (message_type_value = 'AnimalPresenceObstruction' OR (message_type_value = 'Accident' AND message ~* '(vilt|älg|rådjur|hjort|vildsvin|renar|ren )'))), par AS (SELECT DISTINCT ON (p.event_id) p.event_id, t.message_type_value AS trv_typ, extract(epoch FROM p.datetime - t.start_time) / 60 AS polis_minus_trv_min FROM p JOIN t ON t.vag = p.vag AND t.start_time BETWEEN p.datetime - interval '3 hours' AND p.datetime + interval '3 hours' AND ST_DWithin(t.geom::geography, p.geom::geography, 150000) ORDER BY p.event_id, abs(extract(epoch FROM p.datetime - t.start_time))) SELECT count(*) AS par, (SELECT count(*) FROM p) AS polis_med_vagnummer, count(*) FILTER (WHERE trv_typ = 'Accident') AS trv_som_olycka, count(*) FILTER (WHERE trv_typ = 'AnimalPresenceObstruction') AS trv_som_djur, count(*) FILTER (WHERE polis_minus_trv_min > 0) AS trv_forst, count(*) FILTER (WHERE polis_minus_trv_min < 0) AS polisen_forst, round(percentile_cont(0.5) WITHIN GROUP (ORDER BY polis_minus_trv_min)::numeric, 1) AS median_polis_minus_trv_min, round(percentile_cont(0.25) WITHIN GROUP (ORDER BY polis_minus_trv_min)::numeric, 1) AS kvartil1, round(percentile_cont(0.75) WITHIN GROUP (ORDER BY polis_minus_trv_min)::numeric, 1) AS kvartil3 FROM par
