-- KARANTÄNVAKTEN PRÖVAD MOT ARKIVET (kort #234, DECISIONS #298, 21/9 2026).
-- Fyndet i givarvakt-kandidater: de sju stationer som läcker förbi #75:s vakt är SAMMA stationer som andra stunder bryter
-- mot den grovt (yta −46…−50 °C = urkopplad givare). Idén: en station som nyligen brutit mot #75 (yta < luft − 12) får
-- inte tala förrän den mätt rätt en tid. Ingen ny fysikalisk gräns — talet 12 står kvar och får ett MINNE.
-- Varför inte en ren gräns i (luft, gap): blankis i töväder håller ytan vid 0 °C medan luften är +8…+10 — ett ÄKTA gap på
-- 8–10 °C, och det farligaste väglaget. En gräns som tar givarfelen tar också det.
-- Sats 1: för varje rad som i dag kan publiceras som kall (yta <= 3, förbi #75): hur många brott mot #75 gjorde stationen
-- under de D dygnen före? FEL = gap >= 5 (alla sådana rader kommer från de sju stationerna), ÄKTA = gap < 5.
-- Sats 2: vilka ÄKTA stationer skulle tystas, och av vad? Bara läsande.
-- Kör: varje sats på en rad i dbknapp (atgard migrera, fil sql/022_driver_facit.sql, bevis = satserna).

SET statement_timeout = '300s'

WITH brott AS (SELECT station_id, sample_time FROM weather_observations WHERE sample_time > now() - interval '60 days' AND air_temp_c IS NOT NULL AND surface_temp_c < air_temp_c - 12), r AS (SELECT w.station_id, w.sample_time, (w.air_temp_c - w.surface_temp_c >= 5) AS fel, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '1 day') AS b1, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '3 days') AS b3, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '7 days') AS b7, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '14 days') AS b14 FROM weather_observations w WHERE w.sample_time > now() - interval '46 days' AND w.surface_temp_c <= 3 AND w.air_temp_c IS NOT NULL AND w.surface_temp_c >= w.air_temp_c - 12), k(dygn, minst) AS (VALUES (1, 1), (1, 3), (3, 1), (3, 3), (7, 1), (7, 3), (14, 1), (14, 3)) SELECT k.dygn, k.minst, count(*) FILTER (WHERE r.fel) AS felrader, count(*) FILTER (WHERE r.fel AND (CASE k.dygn WHEN 1 THEN r.b1 WHEN 3 THEN r.b3 WHEN 7 THEN r.b7 ELSE r.b14 END) >= k.minst) AS felrader_tagna, count(*) FILTER (WHERE NOT r.fel) AS akta_rader, count(*) FILTER (WHERE NOT r.fel AND (CASE k.dygn WHEN 1 THEN r.b1 WHEN 3 THEN r.b3 WHEN 7 THEN r.b7 ELSE r.b14 END) >= k.minst) AS akta_rader_tystade, count(DISTINCT r.station_id) FILTER (WHERE NOT r.fel AND (CASE k.dygn WHEN 1 THEN r.b1 WHEN 3 THEN r.b3 WHEN 7 THEN r.b7 ELSE r.b14 END) >= k.minst) AS akta_stationer_tystade FROM r CROSS JOIN k GROUP BY 1, 2 ORDER BY 1, 2

WITH brott AS (SELECT station_id, sample_time FROM weather_observations WHERE sample_time > now() - interval '60 days' AND air_temp_c IS NOT NULL AND surface_temp_c < air_temp_c - 12), r AS (SELECT w.station_id, w.name, w.sample_time, w.air_temp_c - w.surface_temp_c AS gap, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '7 days') AS b7 FROM weather_observations w WHERE w.sample_time > now() - interval '46 days' AND w.surface_temp_c <= 3 AND w.air_temp_c IS NOT NULL AND w.surface_temp_c >= w.air_temp_c - 12) SELECT station_id, name, count(*) AS rader, count(*) FILTER (WHERE gap >= 5) AS felrader, count(*) FILTER (WHERE b7 >= 3) AS tagna_av_7_3, count(*) FILTER (WHERE gap >= 5 AND b7 < 3) AS felrader_kvar, count(*) FILTER (WHERE gap < 5 AND b7 >= 3) AS akta_tystade, max(b7) AS flest_brott_7d FROM r GROUP BY 1, 2 HAVING count(*) FILTER (WHERE gap >= 5) > 0 OR count(*) FILTER (WHERE b7 >= 1) > 0 ORDER BY felrader DESC, rader DESC
