-- KARANTÄN + RADVAKT TILLSAMMANS (kort #234, DECISIONS #298, 21/9 2026).
-- Karantänen (>= 3 brott mot #75 på 7 dygn) tar de urkopplade givarna men missar 1106 Ö Ljungby, som ligger ~12 °C fel utan
-- att bryta grovt. Radvakten (luft >= A OCH luft − yta >= 8) tar den — men bara när luften är varm, så att stationen får
-- tala igen när det kyls av. Frågan: vad blir kvar med A = 8 respektive A = 10, och tystas någon äkta rad?
-- Sats 2: vad blir kvar av 1106, och kan det fyra broregeln (yta <= 3)? Bara läsande.
-- Kör: varje sats på en rad i dbknapp (atgard migrera, fil sql/022_driver_facit.sql, bevis = satserna).

SET statement_timeout = '300s'

WITH brott AS (SELECT station_id, sample_time FROM weather_observations WHERE sample_time > now() - interval '60 days' AND air_temp_c IS NOT NULL AND surface_temp_c < air_temp_c - 12), r AS (SELECT w.station_id, w.air_temp_c AS luft, w.air_temp_c - w.surface_temp_c AS gap, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '7 days') >= 3 AS karantan FROM weather_observations w WHERE w.sample_time > now() - interval '46 days' AND w.surface_temp_c <= 3 AND w.air_temp_c IS NOT NULL AND w.surface_temp_c >= w.air_temp_c - 12), k(a) AS (VALUES (8), (10)) SELECT k.a AS radvakt_luft_minst, count(*) FILTER (WHERE r.gap >= 5) AS felrader, count(*) FILTER (WHERE r.gap >= 5 AND (r.karantan OR (r.luft >= k.a AND r.gap >= 8))) AS felrader_tagna, count(*) FILTER (WHERE r.gap >= 5 AND NOT r.karantan AND NOT (r.luft >= k.a AND r.gap >= 8)) AS felrader_kvar, count(DISTINCT r.station_id) FILTER (WHERE r.gap >= 5 AND NOT r.karantan AND NOT (r.luft >= k.a AND r.gap >= 8)) AS stationer_kvar, count(*) FILTER (WHERE r.gap < 5 AND (r.karantan OR (r.luft >= k.a AND r.gap >= 8))) AS akta_rader_tystade FROM r CROSS JOIN k GROUP BY 1 ORDER BY 1

WITH brott AS (SELECT station_id, sample_time FROM weather_observations WHERE sample_time > now() - interval '60 days' AND air_temp_c IS NOT NULL AND surface_temp_c < air_temp_c - 12), r AS (SELECT w.station_id, w.name, (w.sample_time AT TIME ZONE 'UTC')::date AS dag, w.surface_temp_c AS yta, w.air_temp_c AS luft, w.air_temp_c - w.surface_temp_c AS gap, (w.rain OR w.snow OR (w.precipitation IS NOT NULL AND w.precipitation <> '' AND lower(w.precipitation) NOT IN ('no', 'dry'))) AS fukt, (SELECT count(*) FROM brott b WHERE b.station_id = w.station_id AND b.sample_time < w.sample_time AND b.sample_time >= w.sample_time - interval '7 days') >= 3 AS karantan FROM weather_observations w WHERE w.sample_time > now() - interval '46 days' AND w.surface_temp_c <= 3 AND w.air_temp_c IS NOT NULL AND w.surface_temp_c >= w.air_temp_c - 12 AND w.air_temp_c - w.surface_temp_c >= 5) SELECT station_id, name, count(*) AS kvar_med_10, count(*) FILTER (WHERE fukt) AS varav_fuktiga, count(DISTINCT dag) AS dagar, min(luft) AS luft_min, max(luft) AS luft_max, min(gap) AS gap_min, max(gap) AS gap_max, count(*) FILTER (WHERE luft >= 8) AS varav_luft_minst_8 FROM r WHERE NOT karantan AND NOT (luft >= 10 AND gap >= 8) GROUP BY 1, 2 ORDER BY 3 DESC
