-- DEN LÅNGSAMMA VAKTEN, ALTERNATIV (d) — MÄTT INNAN DEN BYGGS (bedömningen §4.2, kort #234:s efterfråga, Bengts ja 22/9).
-- Frågan: hur många stationsdygn i arkivet har haft ytan ≥ 6 ° under luften i mer än ett dygn, vilka stationer, hur stor del
-- av tiden regnade det, och kan något av fallen vara äkta (blixthalka och töväder varar timmar, inte dygn)?
-- Sats 2: SAMMANHÄNGANDE episoder (bryts av en rad med gap < 6 eller ett hål > 3 h) längre än 24 h, med väderläget i varje.
-- Sats 3: RULLANDE fönster — rader där ≥ 90 % av de senaste 24 timmarnas rader (minst 24) har gap ≥ 6; räknat i stationsdygn.
-- Sats 4: svepet över gränsen 5/6/8 ° och andelen 80/90/100 % — hur många stationer tar varje form, och vilka.
-- Sats 5: läget just nu för de sju anmälda stationerna i det rullande fönstret.
-- Bara läsande. Kör: varje sats på en rad i dbknapp (atgard migrera, fil sql/022_driver_facit.sql, bevis = satserna).

SET statement_timeout = '300s'

WITH r AS (SELECT station_id, name, sample_time, air_temp_c - surface_temp_c AS gap, (rain OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry'))) AS regn, surface_temp_c AS yta, air_temp_c AS luft, lag(sample_time) OVER w AS f_tid, lag(air_temp_c - surface_temp_c) OVER w AS f_gap FROM weather_observations WHERE air_temp_c IS NOT NULL AND surface_temp_c IS NOT NULL WINDOW w AS (PARTITION BY station_id ORDER BY sample_time)), m AS (SELECT *, sum(CASE WHEN gap >= 6 AND (f_gap IS NULL OR f_gap < 6 OR sample_time - f_tid > interval '3 hours') THEN 1 ELSE 0 END) OVER (PARTITION BY station_id ORDER BY sample_time) AS ep FROM r), e AS (SELECT station_id, name, ep, min(sample_time) AS start, max(sample_time) AS slut, count(*) AS rader, round(avg(CASE WHEN regn THEN 1 ELSE 0 END)::numeric, 2) AS regnandel, round(avg(gap), 1) AS gap_medel, min(gap) AS gap_min, max(gap) AS gap_max, min(yta) AS yta_min, max(yta) AS yta_max, min(luft) AS luft_min, max(luft) AS luft_max FROM m WHERE gap >= 6 GROUP BY 1, 2, 3) SELECT station_id, name, to_char(start AT TIME ZONE 'UTC', 'MM-DD HH24:MI') AS start, round((extract(epoch FROM slut - start) / 3600)::numeric, 1) AS timmar, rader, regnandel, gap_medel, gap_min, gap_max, yta_min, yta_max, luft_min, luft_max FROM e WHERE slut - start > interval '24 hours' ORDER BY timmar DESC

WITH r AS (SELECT station_id, name, sample_time, (air_temp_c - surface_temp_c >= 6)::int AS stort, (rain OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry')))::int AS regn FROM weather_observations WHERE air_temp_c IS NOT NULL AND surface_temp_c IS NOT NULL), w AS (SELECT station_id, name, sample_time, count(*) OVER f AS n24, sum(stort) OVER f AS stort24, sum(regn) OVER f AS regn24 FROM r WINDOW f AS (PARTITION BY station_id ORDER BY sample_time RANGE BETWEEN interval '24 hours' PRECEDING AND CURRENT ROW)) SELECT station_id, name, count(DISTINCT (sample_time AT TIME ZONE 'UTC')::date) AS dygn, count(*) AS rader, min(sample_time)::date AS forsta, max(sample_time)::date AS senaste, round(avg(regn24::numeric / n24), 2) AS regnandel FROM w WHERE n24 >= 24 AND stort24 >= 0.9 * n24 GROUP BY 1, 2 ORDER BY dygn DESC, rader DESC

WITH r AS (SELECT station_id, sample_time, air_temp_c - surface_temp_c AS gap FROM weather_observations WHERE air_temp_c IS NOT NULL AND surface_temp_c IS NOT NULL), p(g) AS (VALUES (5), (6), (8)), w AS (SELECT p.g, station_id, count(*) OVER f AS n24, sum((gap >= p.g)::int) OVER f AS stort24 FROM r CROSS JOIN p WINDOW f AS (PARTITION BY p.g, station_id ORDER BY sample_time RANGE BETWEEN interval '24 hours' PRECEDING AND CURRENT ROW)) SELECT g AS grans, count(DISTINCT station_id) FILTER (WHERE stort24 >= 0.8 * n24) AS stationer_80, count(DISTINCT station_id) FILTER (WHERE stort24 >= 0.9 * n24) AS stationer_90, count(DISTINCT station_id) FILTER (WHERE stort24 = n24) AS stationer_100, string_agg(DISTINCT station_id, ',') FILTER (WHERE stort24 >= 0.9 * n24) AS stationer_vid_90 FROM w WHERE n24 >= 24 GROUP BY g ORDER BY g

WITH r AS (SELECT station_id, name, sample_time, (air_temp_c - surface_temp_c >= 6)::int AS stort, air_temp_c - surface_temp_c AS gap, (rain OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry')))::int AS regn FROM weather_observations WHERE air_temp_c IS NOT NULL AND surface_temp_c IS NOT NULL AND station_id IN ('1106', '2346', '2135', '1612', '2132', '1713', '1302')), w AS (SELECT station_id, name, sample_time, gap, count(*) OVER f AS n24, sum(stort) OVER f AS stort24, sum(regn) OVER f AS regn24 FROM r WINDOW f AS (PARTITION BY station_id ORDER BY sample_time RANGE BETWEEN interval '24 hours' PRECEDING AND CURRENT ROW)) SELECT DISTINCT ON (station_id) station_id, name, to_char(sample_time AT TIME ZONE 'UTC', 'MM-DD HH24:MI') AS senaste, gap AS gap_nu, n24, stort24, regn24, (stort24 >= 0.9 * n24 AND n24 >= 24) AS d_tystar_nu FROM w ORDER BY station_id, sample_time DESC
