-- Kort #45 steg 1 (Bengts ja 25/9): premissen före tröskeldokumentet. Vilka värden bär Trafikverkets `precipitation` i arkivet,
-- och hur hel är luft/fuktighet/daggpunkt — i alla rader och i nederbördsraderna? RÄKNAR BARA POPULATIONEN: ingen sats korsar
-- nederbördstypen mot temperaturen, så inget utfall läses innan TROSKLAR-NEDERBORDSTYPEN är skrivet. Körs med dbknapp.
-- (Körd 25/9 med NOT IN ('', 'no', 'dry'); omskriven till kontraktsgrindens form för torrorden — samma betydelse.)
SELECT COALESCE(precipitation, '(null)') AS precipitation, count(*) AS rader, count(DISTINCT station_id) AS stationer, count(*) FILTER (WHERE rain) AS rain, count(*) FILTER (WHERE snow) AS snow, to_char(min(sample_time), 'MM-DD') AS forst, to_char(max(sample_time), 'MM-DD HH24:MI') AS senast FROM weather_observations WHERE sample_time > now() - interval '30 days' GROUP BY 1 ORDER BY 2 DESC
SELECT count(*) AS rader, count(DISTINCT station_id) AS stationer, count(air_temp_c) AS luft, count(humidity_pct) AS fukt, count(dewpoint_c) AS dagg, count(*) FILTER (WHERE air_temp_c IS NOT NULL AND (humidity_pct IS NOT NULL OR dewpoint_c IS NOT NULL)) AS vatbulb_mojlig FROM weather_observations WHERE sample_time > '2026-09-25 07:20:00+00'
SELECT count(*) AS nbd_rader, count(DISTINCT station_id) AS stationer, count(*) FILTER (WHERE air_temp_c IS NOT NULL AND humidity_pct IS NOT NULL) AS luft_och_fukt, count(*) FILTER (WHERE air_temp_c IS NOT NULL AND dewpoint_c IS NOT NULL) AS luft_och_dagg FROM weather_observations WHERE sample_time > now() - interval '30 days' AND (rain OR snow OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry')))
SELECT count(DISTINCT station_id) AS alla, count(DISTINCT station_id) FILTER (WHERE humidity_pct IS NOT NULL) AS med_fukt, count(DISTINCT station_id) FILTER (WHERE dewpoint_c IS NOT NULL) AS med_dagg, count(DISTINCT station_id) FILTER (WHERE air_temp_c IS NOT NULL) AS med_luft FROM weather_observations WHERE sample_time > now() - interval '7 days'
SELECT min(air_temp_c) AS luft_min, max(air_temp_c) AS luft_max, min(humidity_pct) AS fukt_min, max(humidity_pct) AS fukt_max, min(dewpoint_c) AS dagg_min, max(dewpoint_c) AS dagg_max, count(*) FILTER (WHERE humidity_pct > 100 OR humidity_pct < 0) AS fukt_utanfor, count(*) FILTER (WHERE dewpoint_c > air_temp_c + 0.5) AS dagg_over_luft FROM weather_observations WHERE sample_time > now() - interval '30 days'
SELECT COALESCE(precipitation, '(null)') AS precipitation, count(*) AS rader, to_char(min(sample_time), 'YYYY-MM-DD') AS forst FROM weather_observations GROUP BY 1 ORDER BY 2 DESC
