-- Radarns bidrag till "vägen är blöt" (efterhalkans premiss), körd 16/9 2026 via dbknapp (körning 35135412610).
-- DECISIONS #218. Enhet: station-timme, 14 dygn, N = 4 h, mätare > 0, radar rate_mean > 0,1 inom 5 km.

SET statement_timeout = '300s';

SELECT min(observed_at) AS radar_fran, max(observed_at) AS radar_till, count(DISTINCT observed_at) AS kompositer, count(*) AS rader FROM radar_precip WHERE observed_at > now() - interval '14 days';

SELECT count(*) AS stationer, count(*) FILTER (WHERE har) AS med_matare, count(*) FILTER (WHERE kall) AS kalla, count(*) FILTER (WHERE kall AND har) AS kalla_med_matare FROM (SELECT station_id, bool_or(rain_sum_mm IS NOT NULL) AS har, bool_or(surface_temp_c <= 5 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12) AS kall FROM weather_observations WHERE sample_time > now() - interval '14 days' GROUP BY 1) s;

WITH st AS (SELECT DISTINCT ON (station_id) station_id, geom FROM weather_observations WHERE sample_time > now() - interval '14 days' AND geom IS NOT NULL ORDER BY station_id, sample_time DESC), nara AS (SELECT DISTINCT st.station_id, rc.segment_id FROM st JOIN road_conditions rc ON NOT rc.deleted AND rc.geom IS NOT NULL AND rc.geom && ST_Expand(st.geom, 0.15) AND ST_DWithin(rc.geom::geography, st.geom::geography, 5000)), radar_h AS (SELECT DISTINCT n.station_id, date_trunc('hour', r.observed_at) AS h FROM radar_precip r JOIN nara n USING (segment_id) WHERE r.observed_at > now() - interval '14 days' AND r.rate_mean_mmh > 0.1), obs_h AS (SELECT station_id, date_trunc('hour', sample_time) AS h, bool_or(rain_sum_mm IS NOT NULL) AS matare, bool_or(rain_sum_mm > 0) AS regn, bool_or(surface_temp_c <= 5 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12) AS kall FROM weather_observations WHERE sample_time > now() - interval '14 days' GROUP BY 1, 2), tid AS (SELECT station_id, h, kall, matare, regn, false AS radar, true AS obs FROM obs_h UNION ALL SELECT station_id, h, false, false, false, true, false FROM radar_h), f AS (SELECT station_id, h, kall, obs, bool_or(matare) OVER w AS matare4, bool_or(regn) OVER w AS regn4, bool_or(radar) OVER w AS radar4 FROM tid WINDOW w AS (PARTITION BY station_id ORDER BY h RANGE BETWEEN interval '3 hours' PRECEDING AND CURRENT ROW)), u AS (SELECT f.*, (f.station_id IN (SELECT station_id FROM nara)) AS radar_mojlig FROM f WHERE obs) SELECT g.grupp, count(*) AS timmar, round(100.0 * avg(matare4::int), 1) AS med_matare_pct, round(100.0 * avg(radar_mojlig::int), 1) AS radar_mojlig_pct, count(*) FILTER (WHERE regn4 OR radar4) AS blota, count(*) FILTER (WHERE regn4 AND radar4) AS bada, count(*) FILTER (WHERE regn4 AND NOT radar4) AS bara_matare, count(*) FILTER (WHERE radar4 AND NOT regn4) AS bara_radar, count(*) FILTER (WHERE radar4 AND NOT regn4 AND NOT matare4) AS bara_radar_utan_matare, count(*) FILTER (WHERE radar4 AND NOT regn4 AND matare4) AS bara_radar_matare_torr, round(100.0 * count(*) FILTER (WHERE radar4 AND NOT regn4) / NULLIF(count(*) FILTER (WHERE regn4 OR radar4), 0), 1) AS forlust_pct FROM u CROSS JOIN LATERAL (VALUES ('alla'), (CASE WHEN u.kall THEN 'yta<=5' END)) g(grupp) WHERE g.grupp IS NOT NULL GROUP BY g.grupp ORDER BY g.grupp;
