-- Mätning 2026-09-17: går efterhalkans regnmängd (minsta regn) och radarn att spela upp i efterhand ur arkivet?
-- Bengt 17/9 (väg C för radarn + pröva regnmängden). Körs via dbknapp (atgard migrera, bevis = satserna nedan).
-- Metod: loggens regn_h räknas om ur weather_observations vid snapshotens tid, med och utan simulerad gallring
-- (sql/014: sista raden per station och 30-min-hink). Radarn kopplas provisoriskt på 5 km, som mätningen 16/9.

SET statement_timeout = '300s';

SELECT count(*) AS korningar, count(*) FILTER (WHERE jsonb_array_length(efterhalka) > 0) AS korningar_med_rader, coalesce(sum(jsonb_array_length(efterhalka)), 0) AS stationsrader, min(run_at) FILTER (WHERE jsonb_array_length(efterhalka) > 0) AS forsta, max(run_at) AS senaste FROM shadow_log WHERE run_at > now() - interval '7 days';

WITH e AS (SELECT DISTINCT s.snapshot_generated_at::timestamptz AS t, x->>'id' AS id, (x->>'regn_h')::float AS logg FROM shadow_log s CROSS JOIN LATERAL jsonb_array_elements(s.efterhalka) x WHERE s.run_at > now() - interval '7 days'), w AS (SELECT station_id, sample_time, rain_sum_mm, row_number() OVER (PARTITION BY station_id, floor(extract(epoch FROM sample_time) / 1800) ORDER BY sample_time DESC) = 1 AS overlever FROM weather_observations WHERE sample_time > now() - interval '9 days' AND station_id IN (SELECT id FROM e)), a AS (SELECT e.t, e.logg, (SELECT max(sample_time) FROM w WHERE w.station_id = e.id AND w.rain_sum_mm > 0 AND w.sample_time <= e.t AND w.sample_time > e.t - interval '48 hours') AS s_full, (SELECT max(sample_time) FROM w WHERE w.station_id = e.id AND w.overlever AND w.rain_sum_mm > 0 AND w.sample_time <= e.t AND w.sample_time > e.t - interval '48 hours') AS s_gallrad, (SELECT max(sample_time) FROM w WHERE w.station_id = e.id AND w.rain_sum_mm >= 0.2 AND w.sample_time <= e.t AND w.sample_time > e.t - interval '48 hours') AS s_02, (SELECT max(sample_time) FROM w WHERE w.station_id = e.id AND w.rain_sum_mm >= 0.5 AND w.sample_time <= e.t AND w.sample_time > e.t - interval '48 hours') AS s_05 FROM e), b AS (SELECT logg, round((extract(epoch FROM t - s_full) / 3600)::numeric, 1)::float AS full_h, round((extract(epoch FROM t - s_gallrad) / 3600)::numeric, 1)::float AS gallrad_h, round((extract(epoch FROM t - s_02) / 3600)::numeric, 1)::float AS h02, round((extract(epoch FROM t - s_05) / 3600)::numeric, 1)::float AS h05 FROM a) SELECT count(*) AS station_ogonblick, count(*) FILTER (WHERE logg IS NOT NULL) AS logg_regn_h_satt, count(*) FILTER (WHERE (logg IS NULL AND full_h IS NULL) OR abs(logg - full_h) <= 0.15) AS lika_full, count(*) FILTER (WHERE (logg IS NULL AND gallrad_h IS NULL) OR abs(logg - gallrad_h) <= 0.15) AS lika_gallrad, count(*) FILTER (WHERE (logg IS NULL AND gallrad_h IS NULL) OR abs(logg - gallrad_h) <= 0.55) AS inom_en_hink_gallrad, max(abs(logg - full_h)) AS max_diff_full_h, count(*) FILTER (WHERE logg <= 2) AS blot_n2_logg, count(*) FILTER (WHERE full_h <= 2) AS blot_n2_full, count(*) FILTER (WHERE gallrad_h <= 2) AS blot_n2_gallrad, count(*) FILTER (WHERE h02 <= 2) AS blot_n2_minst_02, count(*) FILTER (WHERE h05 <= 2) AS blot_n2_minst_05 FROM b;

SELECT count(DISTINCT station_id) FILTER (WHERE rain_sum_mm > 0) AS stationer_med_regn, count(*) FILTER (WHERE rain_sum_mm > 0) AS regnrader, count(*) FILTER (WHERE rain_sum_mm > 0 AND rain_sum_mm < 0.2) AS under_02, count(*) FILTER (WHERE rain_sum_mm >= 0.2 AND rain_sum_mm < 0.5) AS fran_02_till_05, count(*) FILTER (WHERE rain_sum_mm >= 0.5) AS minst_05, min(rain_sum_mm) FILTER (WHERE rain_sum_mm > 0) AS minsta_varde FROM weather_observations WHERE sample_time > now() - interval '7 days' AND surface_temp_c <= 5;

WITH e AS (SELECT DISTINCT s.snapshot_generated_at::timestamptz AS t, x->>'id' AS id, (x->>'regn_h')::float AS logg FROM shadow_log s CROSS JOIN LATERAL jsonb_array_elements(s.efterhalka) x WHERE s.run_at > now() - interval '7 days'), st AS (SELECT DISTINCT ON (station_id) station_id, geom FROM weather_observations WHERE sample_time > now() - interval '9 days' AND station_id IN (SELECT id FROM e) ORDER BY station_id, sample_time DESC), nara AS (SELECT DISTINCT st.station_id, rc.segment_id FROM st JOIN road_conditions rc ON NOT rc.deleted AND rc.geom IS NOT NULL AND rc.geom && ST_Expand(st.geom, 0.15) AND ST_DWithin(rc.geom::geography, st.geom::geography, 5000)), r AS (SELECT e.id, (SELECT max(p.rate_mean_mmh) FROM radar_precip p JOIN nara n ON n.segment_id = p.segment_id AND n.station_id = e.id WHERE p.observed_at <= e.t AND p.observed_at > e.t - interval '2 hours') AS maxrate FROM e) SELECT count(*) AS station_ogonblick, count(*) FILTER (WHERE id IN (SELECT station_id FROM nara)) AS med_vag_inom_5km, count(*) FILTER (WHERE maxrate > 0.1) AS radar_over_01, count(*) FILTER (WHERE maxrate > 0.5) AS radar_over_05, count(*) FILTER (WHERE maxrate > 2) AS radar_over_2 FROM r;

SELECT (SELECT min(observed_at) FROM radar_precip) AS radar_forsta, (SELECT max(observed_at) FROM radar_precip) AS radar_senaste, (SELECT min(sample_time) FROM weather_observations) AS vader_forsta, pg_size_pretty(pg_total_relation_size('radar_precip')) AS radar_storlek, pg_size_pretty(pg_total_relation_size('weather_observations')) AS vader_storlek, pg_size_pretty(pg_database_size(current_database())) AS databas;
