-- SNÖFLINGAN SOM JÄMFÖRELSE (kort #233, DECISIONS #296; Bengts "kör snöflingemätningen nu" 21/9 2026).
-- Frågan: hur stor andel av stationsregelns fyrningar (yta <= +1 °C och fukt, engine.ts:213–218) sker när LUFTEN ligger
-- över +3 °C respektive +4 °C — alltså när bilens egen snöflinga är släckt och bara stationen ser faran?
-- Läser FYRNINGAR, inte utfall: ingen facitkolumn rörs, blindningen (D2/D3/D6) berörs inte.
-- Fukt räknas som publish/snapshot-core.ts: rain eller snow eller en nederbördsklass som inte är "no"/"Dry".
-- Givarvakten #75 på varje rad: lufttemperatur finns och yta >= luft − 12. Episod = stationens första ögonblick per natt,
-- natt = middag till middag UTC (samma räknesätt som sql/028 och T-A). Broregeln (+3 °C) är inte med.
-- Sats 5 är SAMMANHANGET utan fuktkravet: hur ofta är ytan under noll medan luften ligger över +3 °C — fenomenet självt.
-- Kör: varje sats på en rad i dbknapp (atgard migrera, fil sql/022_driver_facit.sql, bevis = satserna). Bara läsande.

SET statement_timeout = '300s'

SELECT min(sample_time) AS fran, max(sample_time) AS till, count(*) AS rader, count(DISTINCT station_id) AS stationer, count(*) FILTER (WHERE surface_temp_c <= 1) AS rader_yta_hogst_1, count(*) FILTER (WHERE surface_temp_c <= 1 AND air_temp_c IS NULL) AS varav_utan_luft FROM weather_observations WHERE sample_time > now() - interval '60 days'

WITH f AS (SELECT station_id, sample_time, surface_temp_c AS yta, air_temp_c AS luft, ((sample_time - interval '12 hours') AT TIME ZONE 'UTC')::date AS natt FROM weather_observations WHERE sample_time > now() - interval '60 days' AND surface_temp_c <= 1 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12 AND (rain OR snow OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry')))), ep AS (SELECT DISTINCT ON (station_id, natt) station_id, natt, yta, luft FROM f ORDER BY station_id, natt, sample_time) SELECT count(*) AS episoder, count(DISTINCT station_id) AS stationer, count(DISTINCT natt) AS natter, count(*) FILTER (WHERE luft > 3) AS luft_over_3, round(100.0 * count(*) FILTER (WHERE luft > 3) / NULLIF(count(*), 0), 1) AS pct_over_3, count(*) FILTER (WHERE luft > 4) AS luft_over_4, round(100.0 * count(*) FILTER (WHERE luft > 4) / NULLIF(count(*), 0), 1) AS pct_over_4, round(avg(luft - yta), 2) AS medel_luft_minus_yta, min(luft) AS luft_min, max(luft) AS luft_max FROM ep

WITH f AS (SELECT station_id, date_trunc('hour', sample_time) AS h, min(air_temp_c) AS luft_min FROM weather_observations WHERE sample_time > now() - interval '60 days' AND surface_temp_c <= 1 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12 AND (rain OR snow OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry'))) GROUP BY 1, 2) SELECT count(*) AS stationstimmar, count(*) FILTER (WHERE luft_min > 3) AS luft_over_3, round(100.0 * count(*) FILTER (WHERE luft_min > 3) / NULLIF(count(*), 0), 1) AS pct_over_3, count(*) FILTER (WHERE luft_min > 4) AS luft_over_4, round(100.0 * count(*) FILTER (WHERE luft_min > 4) / NULLIF(count(*), 0), 1) AS pct_over_4 FROM f

WITH f AS (SELECT station_id, sample_time, air_temp_c AS luft, ((sample_time - interval '12 hours') AT TIME ZONE 'UTC')::date AS natt FROM weather_observations WHERE sample_time > now() - interval '60 days' AND surface_temp_c <= 1 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12 AND (rain OR snow OR (precipitation IS NOT NULL AND precipitation <> '' AND lower(precipitation) NOT IN ('no', 'dry')))), ep AS (SELECT DISTINCT ON (station_id, natt) station_id, natt, luft FROM f ORDER BY station_id, natt, sample_time) SELECT natt, count(*) AS episoder, count(*) FILTER (WHERE luft > 3) AS luft_over_3, round(avg(luft), 1) AS luft_medel FROM ep GROUP BY natt ORDER BY episoder DESC, natt LIMIT 12

WITH f AS (SELECT station_id, surface_temp_c AS yta, air_temp_c AS luft, ((sample_time - interval '12 hours') AT TIME ZONE 'UTC')::date AS natt, sample_time FROM weather_observations WHERE sample_time > now() - interval '60 days' AND surface_temp_c <= 0 AND air_temp_c IS NOT NULL AND surface_temp_c >= air_temp_c - 12), ep AS (SELECT DISTINCT ON (station_id, natt) station_id, natt, yta, luft FROM f ORDER BY station_id, natt, sample_time) SELECT count(*) AS frostepisoder_yta_hogst_0, count(DISTINCT station_id) AS stationer, count(*) FILTER (WHERE luft > 3) AS luft_over_3, round(100.0 * count(*) FILTER (WHERE luft > 3) / NULLIF(count(*), 0), 1) AS pct_over_3, count(*) FILTER (WHERE luft > 0) AS luft_over_0, round(100.0 * count(*) FILTER (WHERE luft > 0) / NULLIF(count(*), 0), 1) AS pct_luft_over_0, round(avg(luft - yta), 2) AS medel_luft_minus_yta FROM ep
