-- Mätning 2026-09-17: går efterhalkans startband (+1…+4 / +1…+6) och SMHI-förlängningen (N_varning) att spela upp i efterhand?
-- Bengt 17/9: "pröva startbandet. går smhi-förlängningen att mäta". Körs via dbknapp (atgard migrera, bevis = satserna nedan).
-- Bara tillgång räknas (rader, fönster, kopplingar) — inte hur ofta en variant skulle fyra (D2/D3).

SET statement_timeout = '300s';

SELECT CASE WHEN surface_temp_c <= 3 THEN 'yta 1..3' WHEN surface_temp_c <= 4 THEN 'yta 3..4' ELSE 'yta 4..6' END AS band, count(*) AS rader, count(DISTINCT station_id) AS stationer, count(*) FILTER (WHERE lutning15_c IS NOT NULL) AS med_l15, count(*) FILTER (WHERE lutning30_c IS NOT NULL) AS med_l30, count(*) FILTER (WHERE lutning60_c IS NOT NULL) AS med_l60, min(observed_at) AS forsta, max(observed_at) AS senaste FROM trend_kandidater GROUP BY 1 ORDER BY 1;

WITH e AS (SELECT DISTINCT s.snapshot_generated_at::timestamptz AS t, x->>'id' AS id, (x->>'lutning15')::float AS l15, (x->>'lutning30')::float AS l30, (x->>'lutning60')::float AS l60 FROM shadow_log s CROSS JOIN LATERAL jsonb_array_elements(s.efterhalka) x WHERE s.run_at > now() - interval '7 days'), k AS (SELECT e.*, tk.observed_at AS k_t, tk.lutning15_c::float AS k15, tk.lutning30_c::float AS k30, tk.lutning60_c::float AS k60 FROM e LEFT JOIN LATERAL (SELECT * FROM trend_kandidater tk WHERE tk.station_id = e.id AND tk.observed_at <= e.t AND tk.observed_at > e.t - interval '60 minutes' ORDER BY tk.observed_at DESC LIMIT 1) tk ON true) SELECT count(*) AS station_ogonblick, count(*) FILTER (WHERE l15 IS NOT NULL OR l30 IS NOT NULL OR l60 IS NOT NULL) AS logg_med_lutning, count(*) FILTER (WHERE k_t IS NOT NULL) AS kandidatrad_finns, count(*) FILTER (WHERE coalesce(abs(l15 - k15) < 0.001, l15 IS NULL AND k15 IS NULL) AND coalesce(abs(l30 - k30) < 0.001, l30 IS NULL AND k30 IS NULL) AND coalesce(abs(l60 - k60) < 0.001, l60 IS NULL AND k60 IS NULL)) AS alla_tre_lika FROM k;

WITH k AS (SELECT station_id, observed_at, CASE WHEN surface_temp_c <= 4 THEN 'yta 3..4' ELSE 'yta 4..6' END AS band FROM trend_kandidater WHERE observed_at > now() - interval '7 days' AND surface_temp_c > 3) SELECT band, count(*) AS rader, count(DISTINCT station_id) AS stationer, count(*) FILTER (WHERE EXISTS (SELECT 1 FROM weather_observations w WHERE w.station_id = k.station_id AND w.rain_sum_mm > 0 AND w.sample_time <= k.observed_at AND w.sample_time > k.observed_at - interval '48 hours')) AS regn_h_gar_att_rakna FROM k GROUP BY band ORDER BY band;

SELECT event_code, level_code, count(*) AS rader, count(*) FILTER (WHERE approx_start IS NOT NULL AND approx_end IS NOT NULL) AS med_fonster, count(*) FILTER (WHERE geom IS NOT NULL) AS med_geometri, min(published) AS forsta, max(published) AS senaste FROM smhi_warnings_history GROUP BY 1, 2 ORDER BY 3 DESC;

WITH e AS (SELECT DISTINCT s.snapshot_generated_at::timestamptz AS t, x->>'id' AS id, (x->>'lutning15')::float AS l15, (x->>'lutning30')::float AS l30, (x->>'lutning60')::float AS l60 FROM shadow_log s CROSS JOIN LATERAL jsonb_array_elements(s.efterhalka) x WHERE s.run_at > now() - interval '7 days'), st AS (SELECT DISTINCT ON (station_id) station_id, geom FROM weather_observations WHERE sample_time > now() - interval '9 days' AND station_id IN (SELECT id FROM e) ORDER BY station_id, sample_time DESC) SELECT count(*) AS station_ogonblick, count(*) FILTER (WHERE EXISTS (SELECT 1 FROM smhi_warnings_history h WHERE h.published <= e.t AND h.approx_start <= e.t AND h.approx_end >= e.t AND ST_Covers(h.geom, st.geom))) AS under_nagon_aktiv_varning, count(*) FILTER (WHERE EXISTS (SELECT 1 FROM smhi_warnings_history h WHERE h.event_code IN ('SNOW_ICE', 'ICING') AND h.published <= e.t AND h.approx_start <= e.t AND h.approx_end >= e.t AND ST_Covers(h.geom, st.geom))) AS under_aktiv_vintervarning FROM e JOIN st ON st.station_id = e.id;

WITH st AS (SELECT DISTINCT ON (station_id) station_id, geom FROM weather_observations WHERE sample_time > now() - interval '2 days' ORDER BY station_id, sample_time DESC), h AS (SELECT event_code, geom FROM smhi_warnings_history WHERE approx_end > now() - interval '5 days' AND approx_start IS NOT NULL AND geom IS NOT NULL) SELECT h.event_code, count(DISTINCT st.station_id) AS stationer_under_varning_5_dygn, (SELECT count(*) FROM st) AS stationer_totalt FROM h JOIN st ON ST_Covers(h.geom, st.geom) GROUP BY h.event_code ORDER BY 2 DESC;

-- Tillägg samma dag: fångas giltighetsfönstret för varningar arkiverade efter sql/015?
SELECT event_code, level_code, count(*) AS rader, count(*) FILTER (WHERE approx_start IS NOT NULL AND approx_end IS NOT NULL) AS med_fonster, min(archived_at) AS forsta_arkiverad, max(archived_at) AS senast_arkiverad FROM smhi_warnings_history WHERE archived_at >= '2026-09-13' GROUP BY 1, 2 ORDER BY 3 DESC;
