-- Uppspelningen ur arkiven — efterhalkans beta (DECISIONS #226, grundversion 2026-09-17, Bengts "kör uppspelningen").
-- Startpunkten (DECISIONS #222/#225): regn inom 2 h (rain_sum_mm > 0) · fall >= 0,8 °C på 30 min (trend_kandidater.lutning30_c,
-- positivt = faller) · yta +1…+3 °C. Talen står EN gång per sats i CTE:n p. Når S3 motorn blir de kod i flera filer och
-- ska då in i scripts/kontraktsgrinden.ts (bedömningen §0b).
-- Sats 1: stationsdygn per dag — i bandet, utan faller, utan blöt, kombinationen. Sats 2: de tio senaste tillfällena.
-- Sats 3: kontrollen — regeln ur skuggloggen (det telefonen såg) mot samma regel ur arkiven, per station-ögonblick.
-- Utfallet läses INTE: startvärdena står till kalibreringen 1/2 (D2/D3). Datum i UTC.
-- Kör: varje sats på en rad i dbknapp (atgard migrera, fil sql/022_driver_facit.sql, bevis = satserna).

SET statement_timeout = '300s';

WITH p AS (SELECT interval '2 hours' AS n, 0.8::numeric AS fall, 1::numeric AS lag, 3::numeric AS hog, interval '14 days' AS fonster), tk AS (SELECT tk.station_id, (tk.observed_at AT TIME ZONE 'UTC')::date AS dag, tk.lutning30_c >= p.fall AS faller, EXISTS (SELECT 1 FROM weather_observations w WHERE w.station_id = tk.station_id AND w.rain_sum_mm > 0 AND w.sample_time <= tk.observed_at AND w.sample_time > tk.observed_at - p.n) AS blot FROM trend_kandidater tk, p WHERE tk.observed_at > now() - p.fonster AND tk.surface_temp_c BETWEEN p.lag AND p.hog), wr AS (SELECT w.station_id, (w.sample_time AT TIME ZONE 'UTC')::date AS dag, EXISTS (SELECT 1 FROM weather_observations r WHERE r.station_id = w.station_id AND r.rain_sum_mm > 0 AND r.sample_time <= w.sample_time AND r.sample_time > w.sample_time - p.n) AS blot FROM weather_observations w, p WHERE w.sample_time > now() - p.fonster AND w.surface_temp_c BETWEEN p.lag AND p.hog AND w.air_temp_c IS NOT NULL AND w.surface_temp_c >= w.air_temp_c - 12 AND (w.air_temp_c < 10 OR w.air_temp_c - w.surface_temp_c < 8) AND (SELECT count(*) FROM weather_observations k WHERE k.station_id = w.station_id AND k.sample_time <= w.sample_time AND k.sample_time > w.sample_time - interval '7 days' AND k.air_temp_c IS NOT NULL AND k.surface_temp_c < k.air_temp_c - 12) < 3 AND NOT EXISTS (SELECT 1 FROM givarfel_dygn g WHERE g.station_id = w.station_id AND g.dag = (w.sample_time AT TIME ZONE 'UTC')::date)), a AS (SELECT dag, count(DISTINCT station_id) AS stationer_i_bandet, count(DISTINCT station_id) FILTER (WHERE blot) AS utan_faller FROM wr GROUP BY dag), b AS (SELECT dag, count(DISTINCT station_id) FILTER (WHERE faller) AS utan_blot, count(DISTINCT station_id) FILTER (WHERE faller AND blot) AS kombinationen, count(*) FILTER (WHERE faller AND blot) AS kombinationen_ogonblick FROM tk GROUP BY dag) SELECT a.dag, a.stationer_i_bandet, a.utan_faller, coalesce(b.utan_blot, 0) AS utan_blot, coalesce(b.kombinationen, 0) AS kombinationen, coalesce(b.kombinationen_ogonblick, 0) AS kombinationen_ogonblick FROM a LEFT JOIN b USING (dag) ORDER BY a.dag;

WITH p AS (SELECT interval '2 hours' AS n, 0.8::numeric AS fall, 1::numeric AS lag, 3::numeric AS hog, interval '14 days' AS fonster) SELECT tk.station_id, to_char(tk.observed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI') AS tid_utc, tk.surface_temp_c AS yta, tk.lutning30_c AS fall30, round(extract(epoch FROM tk.observed_at - r.senast) / 60) AS minuter_sedan_regn FROM trend_kandidater tk CROSS JOIN p CROSS JOIN LATERAL (SELECT max(w.sample_time) AS senast FROM weather_observations w WHERE w.station_id = tk.station_id AND w.rain_sum_mm > 0 AND w.sample_time <= tk.observed_at AND w.sample_time > tk.observed_at - p.n) r WHERE tk.observed_at > now() - p.fonster AND tk.surface_temp_c BETWEEN p.lag AND p.hog AND tk.lutning30_c >= p.fall AND r.senast IS NOT NULL ORDER BY tk.observed_at DESC LIMIT 10;

WITH p AS (SELECT interval '2 hours' AS n, 0.8::numeric AS fall, 1::numeric AS lag, 3::numeric AS hog, interval '14 days' AS fonster), e AS (SELECT DISTINCT s.snapshot_generated_at::timestamptz AS t, x->>'id' AS id, (x->>'yta')::float AS yta, (x->>'regn_h')::float AS regn_h, (x->>'lutning30')::float AS l30 FROM p, shadow_log s CROSS JOIN LATERAL jsonb_array_elements(s.efterhalka) x WHERE s.run_at > now() - p.fonster), k AS (SELECT coalesce(e.yta BETWEEN p.lag AND p.hog AND e.regn_h <= extract(epoch FROM p.n) / 3600 AND e.l30 >= p.fall, false) AS logg, coalesce((SELECT w.surface_temp_c BETWEEN p.lag AND p.hog FROM weather_observations w WHERE w.station_id = e.id AND w.sample_time <= e.t ORDER BY w.sample_time DESC LIMIT 1), false) AND coalesce((SELECT tk.lutning30_c >= p.fall FROM trend_kandidater tk WHERE tk.station_id = e.id AND tk.observed_at <= e.t AND tk.observed_at > e.t - interval '60 minutes' ORDER BY tk.observed_at DESC LIMIT 1), false) AND EXISTS (SELECT 1 FROM weather_observations w WHERE w.station_id = e.id AND w.rain_sum_mm > 0 AND w.sample_time <= e.t AND w.sample_time > e.t - p.n) AS arkiv FROM e, p) SELECT count(*) AS station_ogonblick, count(*) FILTER (WHERE logg AND arkiv) AS bada, count(*) FILTER (WHERE logg AND NOT arkiv) AS bara_loggen, count(*) FILTER (WHERE arkiv AND NOT logg) AS bara_arkivet, count(*) FILTER (WHERE NOT logg AND NOT arkiv) AS ingen FROM k;
